### ISSUE TITLE
In branch vectorObservable, unify classes "observable" and "vectorObservable"

### ISSUE THREAD

**Issue by sebastian-zell** [marco-michel/TimeEvolver#16]
Reorganize structure s.t. instead of arrays, only one observable-class is used both in core and for output. 

The standard-constructor of TimeEvolver should take a vector of observables. There should still be another constructor that takes arrays as observables. It should function in such a way that it creates observables and then calls the first-mentioned constructor. 

The new class should have its own file in the core.

Also one should check if there is too much copying/creating of matrices.

**Comment by marco-michel** [comment]
Solved with the removal of the observable class in 6619ffa.
